<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>cn.managame</groupId><artifactId>mana3</artifactId><version>1.0.0-SNAPSHOT</version></parent><artifactId>game-runtime</artifactId><dependencies><dependency><groupId>cn.managame</groupId><artifactId>game-core</artifactId><version>${project.version}</version></dependency></dependencies></project>
